### ISSUE TITLE
Error compiling crdroid with this kernel for rolex

### ISSUE THREAD

**Issue by javichampi** [muralivijay/android_kernel_xiaomi_msm8917#1]
I have this stupid error when I try to compile crdroid with your sources:

build/kati/fileutil.cc:38: filename.size() < PATH_MAX
11:35:45 ckati failed with: exit status 1

This only happens with your kernel version.

**Comment by ghost** [comment]
You already have a official one? then why again!

**Comment by javichampi** [comment]
Just for testing some tweaks and learn. I have the official version installed for my daily use.

**Comment by muralivijay** [comment]
reclone source . and try to compile properly
